name: labscript
channels:
  - conda-forge
  - defaults
  - labscript-suite
dependencies:
  - blas=1.0=mkl
  - bottleneck=1.3.7=py311hd7041d2_0
  - brotli=1.0.9=h2bbff1b_8
  - brotli-bin=1.0.9=h2bbff1b_8
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2024.3.11=haa95532_0
  - certifi=2024.2.2=py311haa95532_0
  - colorama=0.4.6=py311haa95532_0
  - contourpy=1.2.0=py311h59b6b97_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - desktop-app=0.4.1=py311h82bb817_0
  - distlib=0.3.8=py311haa95532_0
  - fonttools=4.51.0=py311h2bbff1b_0
  - freetype=2.12.1=ha860e81_0
  - h5py=3.11.0=py311h765d3d0_0
  - hdf5=1.12.1=h51c971a_3
  - icc_rt=2022.1.0=h6049295_2
  - icu=73.1=h6c2663c_0
  - importlib-metadata=7.0.1=py311haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - jpeg=9e=h2bbff1b_1
  - kiwisolver=1.4.4=py311hd77b12b_0
  - krb5=1.20.1=h5b6d351_0
  - labscript=3.3.1=py_0
  - labscript-c-extensions=1.1.0=py311h82bb817_0
  - labscript-suite=3.2.0=py_0
  - lcms2=2.12=h83e58a3_0
  - lerc=3.0=hd77b12b_0
  - libbrotlicommon=1.0.9=h2bbff1b_8
  - libbrotlidec=1.0.9=h2bbff1b_8
  - libbrotlienc=1.0.9=h2bbff1b_8
  - libclang=14.0.6=default_hb5a9fac_1
  - libclang13=14.0.6=default_h8e68704_1
  - libdeflate=1.17=h2bbff1b_1
  - libffi=3.4.4=hd77b12b_1
  - libpng=1.6.39=h8cc25b3_0
  - libpq=12.17=h906ac69_0
  - libsodium=1.0.18=h62dcd97_0
  - libtiff=4.5.1=hd77b12b_0
  - libwebp-base=1.3.2=h2bbff1b_0
  - lyse=3.2.3=py_0
  - lz4-c=1.9.4=h2bbff1b_1
  - matplotlib=3.8.4=py311haa95532_0
  - matplotlib-base=3.8.4=py311hf62ec03_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py311h2bbff1b_1
  - mkl_fft=1.3.8=py311h2bbff1b_0
  - mkl_random=1.2.4=py311h59b6b97_0
  - numexpr=2.8.7=py311h1fcbade_0
  - numpy=1.26.4=py311hdab7c0b_0
  - numpy-base=1.26.4=py311hd01c5d8_0
  - openjpeg=2.4.0=h4fc8c34_0
  - openssl=3.0.13=h2bbff1b_2
  - packaging=23.2=py311haa95532_0
  - pandas=2.2.1=py311hea22821_0
  - pillow=10.3.0=py311h2bbff1b_0
  - pip=24.0=py311haa95532_0
  - ply=3.11=py311haa95532_0
  - pybind11-abi=5=hd3eb1b0_0
  - pydaqmx=1.4.6=py_0
  - pynivision=2015.0.0=py_0
  - pyparsing=3.0.9=py311haa95532_0
  - pyqt=5.15.10=py311hd77b12b_0
  - pyqt5-sip=12.13.0=py311h2bbff1b_0
  - pyqtgraph=0.13.1=py311haa95532_0
  - pyserial=3.5=py311haa95532_0
  - python=3.11.9=he1021f5_0
  - python-dateutil=2.9.0post0=py311haa95532_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - pytz=2024.1=py311haa95532_0
  - pyvisa=1.14.1=pyhd8ed1ab_0
  - pywin32=305=py311h2bbff1b_0
  - pyzmq=23.2.0=py311hd77b12b_0
  - qt-main=5.15.2=h19c9488_10
  - qtutils=3.1.0=py_0
  - runmanager=3.2.1=py_0
  - runviewer=3.2.2=py_0
  - scipy=1.13.0=py311h9f229c6_0
  - setuptools=69.5.1=py311haa95532_0
  - setuptools-scm=8.0.4=py311haa95532_0
  - sip=6.7.12=py311hd77b12b_0
  - six=1.16.0=pyhd3eb1b0_1
  - spinapi=3.2.2=py_0
  - sqlite=3.45.3=h2bbff1b_0
  - tbb=2021.8.0=h59b6b97_0
  - tk=8.6.14=h0416ee5_0
  - tornado=6.3.3=py311h2bbff1b_0
  - tqdm=4.66.4=py311h746a85d_0
  - typing-extensions=4.11.0=py311haa95532_0
  - typing_extensions=4.11.0=py311haa95532_0
  - tzdata=2024a=h04d1e81_0
  - tzlocal=5.2=py311haa95532_0
  - unicodedata2=15.1.0=py311h2bbff1b_0
  - vc=14.2=h2eaa2aa_1
  - vs2015_runtime=14.29.30133=h43f2093_3
  - wheel=0.43.0=py311haa95532_0
  - windows-curses=2.3.1=py311h82bb817_0
  - xz=5.4.6=h8cc25b3_1
  - zeromq=4.3.4=hd77b12b_0
  - zipp=3.17.0=py311haa95532_0
  - zlib=1.2.13=h8cc25b3_1
  - zprocess=2.24.0=py311_0
  - zstd=1.5.5=hd43e919_2
  - pip:
      - black==24.4.2
      - blacs==3.3.0.dev6+gfdc4034
      - click==8.1.7
      - labscript-devices==3.3.0.dev12+g0945101
      - labscript-utils==3.4.0.dev12+g851f354
      - mypy-extensions==1.0.0
      - pathspec==0.12.1
      - platformdirs==4.2.2
prefix: C:\ProgramData\miniconda3\envs\labscript
